---
language: node_js

node_js:
  - "7"
  - "8"
  - "9"
sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

install:
  - npm install

script:
  - npm run test
